
* Rope Read

** Motivation

You don't need to move much these days in front of your machine.  Just
press some keys with your fingers and occasionally you possibly stir
the mouse.

But when you read there is this humiliating effort to reposition your
eyeballs to the other end of the line.

- How stressfull is that?
- Isn't this totally depressing?
- This sounds so 2017!

But it's 2018 or even beyound!  Rope Read comes for the
rescue.  Rope Read saves eye movements.

** Try

This is a website realizing a way to rope read.  See
https://marcowahl.github.io/rope-read/ .

- Paste or drop some text into the website.
- See the text in rope read form.
- Then rope read!

** Security

Rope Read runs on your browser.  You are in full control.  No data gets
copied to some other destination.

Okay, this holds as far as I can see.  Of course I can't guarantee
anything.  (This is also stated in the license.)  Note that the

** Free Software

Rope Read is free software.  This includes that you can study this
software and build something on top of it.  (If you do so please drop
me a note!  I'm curious.)

** Links

- Emacs users can try rope-read-mode available via MELPA
  https://melpa.org/#/rope-read-mode.

** Contact

Ideas, feedback and collaboration are typically welcome.

Send mail to marcowahlsoft(a)gmail.com.
